/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject.ui;

import FinalProject.actors.Window;
import gamebase.elements.GraphicContainer;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author aduin
 */
public class Game extends javax.swing.JFrame implements GraphicContainer {

    protected Window window;

    public static final int W_WIDTH = 500;
    public static final int W_HEIGHT = 500;

    private BufferedImage imagenBuffer;
    private Graphics g_imagenBuffer;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        //creamos la imagen en memoria
        imagenBuffer = new BufferedImage(W_WIDTH,W_HEIGHT,BufferedImage.TYPE_INT_RGB);
        //obtenemos los graficos
        g_imagenBuffer = imagenBuffer.getGraphics();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            System.exit(0);
        }

        if (evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            window.keyPressed(evt.getKeyCode());
        }
    } 
public void setWindow(Window window) {
        this.window = window;
    }

    @Override
    public void update(Graphics g) {
        if (window != null) {
            window.paint(g_imagenBuffer);
            g.drawImage(imagenBuffer, 0, 0, this);

        }

    }

    @Override
    public void paint(Graphics g) {
        update(g);

    }

    @Override
    public void refresh() {
        this.repaint();
    }

    @Override
    public Rectangle getBoundaries() {
        return this.getBounds();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
